### ISSUE TITLE
Editing popup displays last geosearch result instead of feature attributes

### ISSUE THREAD

**Issue by sam-berg** [Esri/edit-template#1]
To reproduce, goto edit template:
http://www.arcgis.com/apps/Edit/index.html?webmap=25977874c66c4c0a8dcc181506c6fb45

Type in an address in the search bar, ie. "200 Main St", and select the intellisense entry of  "200 Main St, Iowa City, Iowa, USA", or otherwise find an address.

Now go and click on the editing templates and add a point.

The popup says "200 Main St, Iowa City, Iowa, USA", not the attributes of the feature being edited.  I have not seen the editing template work after an address search.

Thanks you,
Sam

**Comment by agcallis** [comment]
Editing popup displays last geosearch result instead of feature attributes with the updated template. Can this be changed?

**Comment by jgravois** [comment]
it looks like @kellyhutchins merged a fix for this problem on 3/27.  have you tested downloading the latest `.zip`?

**Comment by agcallis** [comment]
I believe the fix was for the previous version of the template. With the updated template, I am getting the same issue. I opened a new issue for the new edit template. Thanks for your help!

**Comment by agcallis** [comment]
![image](https://cloud.githubusercontent.com/assets/5181996/7632490/abf311c6-fa1b-11e4-8bd3-98b7c04d92ff.png)

**Comment by kellyhutchins** [comment]
@agcallis  sorry about this one popping up again. I'll get this fixed for the next release. We switched from the geocoder widget to the search widget and this issue slipped back in.

**Comment by agcallis** [comment]
Thanks @kellyhutchins  for your help!

**Comment by agcallis** [comment]
Do you have an idea when the next release will be??

**Comment by kellyhutchins** [comment]
Not sure of the exact date but before User Conference.
