### ISSUE TITLE
Customizing the HTML - Side panel

### ISSUE THREAD

**Issue by BretWhiteley** [Esri/edit-template#5]
Thank you for assisting me yesterday in adding a custom logo to the header section.  Could you provide a similar snippet to add another graphic, as well as some descriptive (instructive) text to the side panel?  I find that users that are not experienced with web-maps, need to be walked through how to add, or edit features.  I wold thus like to add the following text right above the template picker DIV "To enter a new point on the map, click on a category below and place it on the map".

It would be great if this template could be modified to allow easier customization.  I realize that the template is designed to be responsive to mobile and desktop platforms, but by programmatically creating the content, this however makes it difficult for additional customization.  i.e., I would like to add a GeoCoder and Checkbox's to toggle visible layers.  With the content being created in the "CreateContent.js" file, I would not know how to add these elements to the page.

**Comment by kellyhutchins** [comment]
@BretWhiteley  I just pushed an update to this template that contains search (geocoder) capability. The app has also been slightly re-engineered and might be easier to customize.  For example if you wanted to add some instructions that explain how to use the template you'd want to add code like the following to drawer.js right above the code that creates the editor content pane (approx line 170). 

                var desc = new ContentPane({
                    region: "top",
                    style: "border:none;",
                    content: "<div>Instructions for how to use template go here</div>"
                });
                this._contentPaneSide.addChild(desc);
